spring:
  application:
    name: BuddyBound

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/buddy_bound?createDatabaseIfNotExist=true

  data:
    redis:
      host: localhost
      port: 6379
      password: vanphudh2003

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: levanphu2003248@gmail.com
    password: nocbemlaobwuxsxr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

  session:
    timeout: 1800
