spring:
  profiles:
    active: develop
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: BuddyBound

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # Set to true in production

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PW:123456}
    url: ${DB_URL:jdbc:mysql://localhost:3306/buddy_bound?createDatabaseIfNotExist=true}

    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

    driver-class-name: com.mysql.cj.jdbc.Driver


#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
#      connect-timeout: 60000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
    protocol: smtp
    default-encoding: UTF-8

  session:
    timeout: 1800

jwt:
  secret: fw/xG>MAp-boAO4

api:
  prefix: api/v1

imagekit:
  private-key: ${IMAGEKIT_PRIVATE_KEY}
  public-key: ${IMAGEKIT_PUBLIC_KEY}
  url-endpoint: ${IMAGEKIT_URL}

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: com.mobile.buddybound.controller
  swagger-ui:
    filter: true
    tags-sorter: alpha
    operations-sorter: method
    try-it-out-enabled: true