spring:
  profiles:
    active: develop

  application:
    name: BuddyBound

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PW:123456}
    url: ${DB_URL:jdbc:mysql://localhost:3306/buddy_bound?createDatabaseIfNotExist=true}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:vanphudh2003}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

  session:
    timeout: 1800

  liquibase:
    change-log: classpath:db/changelog/changelog-master.mysql.sql
    enabled: true
